$('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    nav:false,
    responsiveClass:true,
    responsive:{
        0:{
            items:1
        },
        400:{
            items:2
        },
        600:{
            items:3
        },
        800:{
            items:4,
            loop:false
        },
        1000:{
            items:5,
            loop:false
        },
        1200:{
            items:6,
            loop:false
        }
    }
})